// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function ConnectCloud(arg1:string):Promise<Record<string, any>>;

export function ExecuteKql(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetDefaultLocalPath():Promise<string>;

export function GetGitRemote(arg1:string):Promise<string>;

export function GetGitStatus(arg1:string):Promise<Array<main.FileChange>>;

export function GetLocalRuleContent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function GetLocalRulesList(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<string>>;

export function GetLocalWatchlistData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.WatchlistLocalData>;

export function GetLocalWatchlistsList(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<string>>;

export function GetSubscriptions():Promise<Array<models.AzureSubscription>>;

export function GetWorkspaces(arg1:string):Promise<Array<models.AzureWorkspace>>;

export function GitPull(arg1:string):Promise<string>;

export function GitPush(arg1:string,arg2:string):Promise<string>;

export function LoginAzure():Promise<string>;

export function MigrateSelectedRulesToAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:Array<string>):Promise<main.MigrationResult>;

export function MigrateSelectedWatchlistsToAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:Array<string>):Promise<Record<string, any>>;

export function PullWatchlistsFromAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function PushRulesToAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function PushSingleRuleToAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function PushWatchlistsToAzure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function RunPullSync(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SaveLocalRuleKql(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function SaveLocalRuleMarkdown(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function SaveLocalWatchlistData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function ScanLocalContexts(arg1:string):Promise<Array<main.LocalContext>>;

export function SelectLocalRepoPath():Promise<string>;

export function SelectTenant(arg1:string):Promise<Array<models.AzureSubscription>>;

export function SetGitRemote(arg1:string,arg2:string):Promise<void>;
