// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectCloud(arg1) {
  return window['go']['main']['App']['ConnectCloud'](arg1);
}

export function ExecuteKql(arg1, arg2) {
  return window['go']['main']['App']['ExecuteKql'](arg1, arg2);
}

export function GetDefaultLocalPath() {
  return window['go']['main']['App']['GetDefaultLocalPath']();
}

export function GetGitRemote(arg1) {
  return window['go']['main']['App']['GetGitRemote'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetLocalRuleContent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetLocalRuleContent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetLocalRulesList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetLocalRulesList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLocalWatchlistData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetLocalWatchlistData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetLocalWatchlistsList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetLocalWatchlistsList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetWorkspaces(arg1) {
  return window['go']['main']['App']['GetWorkspaces'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1, arg2) {
  return window['go']['main']['App']['GitPush'](arg1, arg2);
}

export function LoginAzure() {
  return window['go']['main']['App']['LoginAzure']();
}

export function MigrateSelectedRulesToAzure(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['MigrateSelectedRulesToAzure'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function MigrateSelectedWatchlistsToAzure(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['MigrateSelectedWatchlistsToAzure'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function PullWatchlistsFromAzure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PullWatchlistsFromAzure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PushRulesToAzure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PushRulesToAzure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PushSingleRuleToAzure(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['PushSingleRuleToAzure'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PushWatchlistsToAzure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PushWatchlistsToAzure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunPullSync(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunPullSync'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveLocalRuleKql(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveLocalRuleKql'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveLocalRuleMarkdown(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveLocalRuleMarkdown'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveLocalWatchlistData(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveLocalWatchlistData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ScanLocalContexts(arg1) {
  return window['go']['main']['App']['ScanLocalContexts'](arg1);
}

export function SelectLocalRepoPath() {
  return window['go']['main']['App']['SelectLocalRepoPath']();
}

export function SelectTenant(arg1) {
  return window['go']['main']['App']['SelectTenant'](arg1);
}

export function SetGitRemote(arg1, arg2) {
  return window['go']['main']['App']['SetGitRemote'](arg1, arg2);
}
